name: Deploy Carenbit

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: test
        run: echo "working runner............"
