name: Deploy Carenbit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
